### ISSUE TITLE
Allow create folder for new project

### ISSUE THREAD

**Issue by velara3** [neminovno/vscode-as-fx-ide#1]
I am attempting to create a new ActionScript project and I select asfx: New Flex/ActionScript Project as shown:

![image](https://user-images.githubusercontent.com/1084127/57908377-b01f8900-7834-11e9-8592-649f56c55d9d.png)

I press the Enter key and a new view is shown: 
![image](https://user-images.githubusercontent.com/1084127/57908505-f4128e00-7834-11e9-93b5-22392ce360a3.png)

I press enter again and it pops up a window with an old project that says: 

>Before creating new project, all files will be deleted in:
>/Users/user/Documents/MyOldProject
>Continue? Yes | No | Cancel

I do not want to use the old project. How do I pick a new folder location?

**Comment by neminovno** [comment]
Currently only existing folder(s) from opened workspace are available to choose.
You would like an option to choose "New folder" location outside of workspace? If yes, then what: add option to add "New folder" to opened workspace (if any), or to open "New folder" in VSCode (new window) after project files creation?

**Comment by velara3** [comment]
> You would like an option to choose "New folder" location outside of workspace? If yes, then what: add option to add "New folder" to opened workspace (if any), or to open "New folder" in VSCode (new window) after project files creation?

Yes. I am interested in the first option but second option might work for others. 
 - New folder (user picks any place on HD)
 - Existing folder in workspace

I see two scenarios. I'm looking at it from the first case but the second case may be desired too.

**Use Case**
Alan is new to Visual Studio Code and AS3 but he wants to create a new AS3 project. He opens VSC, opens the command palette to use asfx: New Flex / AS3 project. He has no workspace or project. ASFX let's him create a directory or pick an existing location. He doesn't have to leave VSC to create his project. 

**Use Case**
Greg is an experienced Visual Studio Code user and wants to create a new AS3 project in his existing workspace. He opens asfx; New Flex / AS3 project and choose Existing folder in workspace.

**Comment by neminovno** [comment]
There are many options, so I am still thinking about it.
Maybe this would be good for last step, if selected project folder is not currently opened in VSCode:
![image](https://user-images.githubusercontent.com/1468887/58054136-f0934580-7b59-11e9-999b-29b3cdaae57f.png)

**Comment by velara3** [comment]
Yes. These are good.

**Comment by neminovno** [comment]
One problem is: if VSCode is started, no folder is opened, new project is created, and on last step user clicks "Add to workspace and open", it will open it, but Explorer panel is not visible, so user may not recognize that something happened. If I find a way to show/open Explorer panel, I will leave "Add to workspace and open" or if not, it will be available only if there is already folder or workspace opened.

**Comment by neminovno** [comment]
Done in v0.3.1
