### ISSUE TITLE
Create project in existing folder without deleting

### ISSUE THREAD

**Issue by velara3** [neminovno/vscode-as-fx-ide#2]
I open the command palette and choose asfx: New Flex/ActionScript Project. 

It is not showing any options to pick a folder but it shows an old project. 

If I select the old project it shows a message: 

>Before creating new project, all files will be deleted in:
>/Users/user/Documents/MyOldProject
>Continue? Yes | No | Cancel

Why do all files have to be deleted? Also, what is the difference between pressing the Cancel button and pressing No?

**Comment by neminovno** [comment]
> Why do all files have to be deleted?

Alternative would be adding extra option like "continue without deleting any files" but it will overwrite _asconfig.json_, _.vscode/launch.json_, _.vscode/tasks.json_, _src/main app file_ and _src/app descriptor file_ (if project needs one). Would that be ok in your opinion?

> Also, what is the difference between pressing the Cancel button and pressing No?

There is no difference. As I remember, Cancel is added by VSCode, to cancel command execution, on any prompt. Maybe I could just remove "No". Or leave "No", and if it is clicked then prompt user again with "overwrite" option.

**Comment by velara3** [comment]
>Alternative would be adding extra option like "continue without deleting any files" but it will overwrite asconfig.json, .vscode/launch.json, .vscode/tasks.json, src/main app file and src/app descriptor file (if project needs one). Would that be ok in your opinion?

Yes

>As I remember, Cancel is added by VSCode, to cancel command execution, on any prompt. Maybe I could just remove "No". Or leave "No", and if it is clicked then prompt user again with "overwrite" option.

Does the extension delete all files in the directory before it starts? Otherwise I would change the prompt from "All files will be deleted" to something like "Any existing related Flex / ActionScript project files in the directory will be over written." You could probably drop the No button.

**Comment by neminovno** [comment]
As I see it, this would be good way:
If target folder is empty, nothing is displayed. If it is not empty, following warning is displayed:
![image](https://user-images.githubusercontent.com/1468887/58043281-15c58b00-7b3d-11e9-94f7-4934fd8a4264.png)

**Comment by neminovno** [comment]
Done in v0.3.1

**Comment by velara3** [comment]
Way to go :)
