### ISSUE TITLE
Can a New ActionScript Project show up in the File menu item?

### ISSUE THREAD

**Issue by velara3** [neminovno/vscode-as-fx-ide#3]
In nearly every application you can go to File > New Project and that starts the process of creating a new project. In VS Code there's New File and New Window but no New Project. 

Is it possible for you to add New Project in the File menu for ActionScript projects and the other types your extension creates?

**Comment by neminovno** [comment]
It looks it is not (yet) possible. Only [these menus](https://code.visualstudio.com/api/references/contribution-points#contributes.menus) are available for extensions:

> Currently extension writers can contribute to:
> 
> - The global Command Palette - commandPalette
> - The Explorer context menu - explorer/context
> - The editor context menu - editor/context
> - The editor title menu bar - editor/title
> - The editor title context menu - editor/title/context
> - The debug callstack view context menu - debug/callstack/context
> - The debug toolbar - debug/toolbar
> - The SCM title menu - scm/title
> - SCM resource groups menus - scm/resourceGroup/context
> - SCM resources menus - scm/resource/context
> - SCM change title menus - scm/change/title
> - The View title menu - view/title
> - The View item menu - view/item/context
> - The macOS Touch Bar - touchBar
>

**Comment by velara3** [comment]
I added a related `New Project` feature request https://github.com/microsoft/vscode/issues/74014.

Someone else also added related `Context Menu` feature request https://github.com/microsoft/vscode/issues/74013

**Comment by neminovno** [comment]
Ok, that is for top level menu. But, you do know that there is already menu item if you right click anywhere in Explorer panel?
![image](https://user-images.githubusercontent.com/1468887/58056533-bc238780-7b61-11e9-93e9-8232709c9ad8.png)

**Comment by velara3** [comment]
I didn't see that before. That's very useful.

**Comment by neminovno** [comment]
Oh ok. I wondered why you want it in top level menu. I doubt VSCode will allow that soon.
From [README](https://github.com/neminovno/vscode-as-fx-ide#new-project-command):
![image](https://user-images.githubusercontent.com/1468887/58056845-e9246a00-7b62-11e9-92c7-87b9097a816e.png)

**Comment by velara3** [comment]
I'm writing a few getting started guides,
- How to create a desktop project with Electron and Royale in Visual Studio Code [here](https://royale.apache.org/how-to-create-a-desktop-application-with-royale-and-electron/)
- How to create an AS3 project in Visual Studio Code ([video here](https://www.youtube.com/watch?v=31aI3ie2Yps))

So some users will come from Flash Builder / Eclipse IDE. In that IDE you had an option to create new projects. You would go to File > New Project > [List of projects here]. 

When I started using Visual Studio Code it was confusing. Where do I create a new project? Why do I have to open a folder? Why do I have to create all the project files myself? What is a command palette? Why are new projects listed in the context menu but not the top level menu? 

People say, it's only an editor but the same people then say install these 5 extensions that give it all the features that exist in IDEs lol.

**Comment by neminovno** [comment]
> I'm writing a few getting started guides,
> 
>     * How to create an AS3 project in Visual Studio Code

Where? GitHub? Link? I had similar plan. Something like a table with FB to VSCode comparison (how to do common stuff, keyboard shortcuts...).
 
> 
> So some users will come from Flash Builder / Eclipse IDE. In that IDE you had an option to create new projects. You would go to File > New Project > [List of projects here].
> 
> When I started using Visual Studio Code it was confusing.

Same here. Folder(s) vs workspace(s) was maybe most confusing for me, probably because FB's workspace principle is different.

But hey, it is a great thing that there is (most?) popular extendable editor and @joshtynjala's [ActionScript & MXML language extension](https://github.com/BowlerHatLLC/vscode-as3mxml) for it. One can easily create snippets like [Flex (MX & Spark) snippets for Visual Studio Code](https://github.com/neminovno/vscode-flex-snippets).
As there are FB like specific menus missing, that make development faster, this extension is created. Further work would be to have these also in a menu:
- Create new Component
- Create new Skin
- Create new Interface
...

> People say, it's only an editor but the same people then say install these 5 extensions that give it all the features that exist in IDEs lol.

Well, maybe [Extension Pack](https://code.visualstudio.com/blogs/2017/03/07/extension-pack-roundup) is the solution for that?

**Comment by velara3** [comment]
> Where? GitHub? Link? 

I haven't created it. I don't know where I'll post it yet but probably on Github. If you put it on Github you're welcome to help on it or I can help if you post it. A few of them will be related to the Web Export plugin I've written for XD. I won't be doing a FB to VSC table / guide. 

> Well, maybe Extension Pack is the solution for that?

An extension pack would be great for new Visual Studio Code Flex / AS3 developers. If you create one I'll link to it. 

Adding Josh's and your extensions would be a good starting pack.

**Comment by neminovno** [comment]
@velara3 Here is [Flex and ActionScript Extension Pack](https://marketplace.visualstudio.com/items?itemName=neminovno.flex-and-actionscript-extension-pack).

**Comment by joshtynjala** [comment]
It might be worth checking out this new extension from Microsoft for some inspiration:

https://blogs.windows.com/buildingapps/2019/05/15/announcing-microsoft-web-template-studio/
https://github.com/Microsoft/WebTemplateStudio/

**Comment by neminovno** [comment]
@joshtynjala thanks. That is not directly related to the issue, right? Main point here is to the [Webview API](https://code.visualstudio.com/api/extension-guides/webview) as alternative to showing QuickInput's in a row?

**Comment by joshtynjala** [comment]
Since there's no general forum, and this issue had some random discussion about creating new projects, I thought it was vaguely relevant enough to mention it here.

**Comment by velara3** [comment]
@neminovno I've published the first post [here](https://royale.apache.org/how-to-create-a-desktop-application-with-royale-and-electron/), How to create a desktop app with Electron and Royale. I've mentioned your extension. 

@joshtynjala I've mentioned your extension too. After I wrote it I stumbled upon your post how to transpile your AS3 class to node JS and I saw that Apache Royale is on npm. If there are other tips and tricks like this you should have access to edit that post or email me and I'll update the doc. (nemo feedback welcome too)
