### ISSUE TITLE
Support for Apache Royale and AS3 HTML projects

### ISSUE THREAD

**Issue by velara3** [neminovno/vscode-as-fx-ide#4]
In the project types drop down there are the following projects: 
![image](https://user-images.githubusercontent.com/1084127/58228990-3defee00-7ce5-11e9-8505-e33e8d425cf6.png)

I'd like to see Apache Royale and AS3 and HTML in that list

https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/Create-a-new-ActionScript-project-in-Visual-Studio-Code-that-targets-Apache-Royale

https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/Create-a-new-ActionScript-project-in-Visual-Studio-Code-that-targets-JavaScript-and-HTML

FWIW I might be able to help (reading up on VSC extensions) but don't have an est on it.

**Comment by neminovno** [comment]
Now, this issue opens another topic regarding VS Code and extensions.

[vscode-as3mxml](https://github.com/BowlerHatLLC/vscode-as3mxml) supports:
![image](https://user-images.githubusercontent.com/1468887/58267303-a55c7b00-7d83-11e9-99f8-7df534a7aa0b.png)

In this extension, if I add support for Royale, why not for Feathers also, and so on. Also, if _New Component_ is added, then we should have _New MXML Component_, _New AS Component_, _New Royale Component_, _New Feathers Component_...

Wouldn't that overload menus? Also, what if one only wants Flex&AS3 ?

Also, as [flex-and-actionscript-extension-pack](https://github.com/neminovno/flex-and-actionscript-extension-pack) is created, adding other project types support in this extensions (which is part of flex-and-actionscript-extension-pack) would not be only Flex&AS3.

Also, if one is using Royale, all snippets from [vscode-flex-snippets](https://github.com/neminovno/vscode-flex-snippets) (which is also part of flex-and-actionscript-extension-pack) would be unnecessary.

As I remember, similar is the reason why @joshtynjala didn't implement this into vscode-as3mxml.

Yes, I could add settings for this extension, like `enableFlex`, `enableRoyale`, `enableFeathers`, so user can enable/disable wanted ones, but probably this is not good way to do it.

So, probably the best way to go, for example for Royale, would be:
- create another extension like this one for Royale ([Your First Extension](https://code.visualstudio.com/api/get-started/your-first-extension) and one can copy my code and change it a little bit)
- create Royale snippets extensions (or use [royalesnippetsforvscode](https://github.com/piotrzarzycki21/royalesnippetsforvscode))
- and, if needed, create Apache Royale Extension Pack which includes vscode-as3mxml and those 2 extensions (very easy to do: [How do I make an Extension Pack?](https://code.visualstudio.com/blogs/2017/03/07/extension-pack-roundup#_how-do-i-make-an-extension-pack))

Same would be for Feathers.

**Comment by velara3** [comment]
Hmm... I'll consider it. Is the [flex-and-actionscript-extension-pack](https://github.com/neminovno/flex-and-actionscript-extension-pack) extension pack on the marketplace? If I make an extension pack can I put it on the market place?

**Comment by neminovno** [comment]
Yes. https://marketplace.visualstudio.com/items?itemName=neminovno.flex-and-actionscript-extension-pack
Yes.
